'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ContableWeb

    '''<summary>
    '''ulTablas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ulTablas As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ulProcesos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ulProcesos As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ulReportes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ulReportes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ContentTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentTitulo As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''contentCuerpo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contentCuerpo As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
